movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movie/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name


movie/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']


movie/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movies=Movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movies=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movies':movies})

def add_movie(request):
    if request.method=='POST':
        n=request.POST.get('name')
        d=request.POST.get('desc')
        y=request.POST.get('year')
        i=request.FILES['img']
        movies=Movie(name=n,desc=d,year=y,img=i)
        movies.save()


    return render(request,'add.html')

def update(request,id):
    movies=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movies':movies})
def delete(request,id):
    if request.method=='POST':
        movies=Movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter the movie name"><br>
    <input type="text" name="desc" placeholder="enter the movie description"><br>
    <input type="text" name="year" placeholder="enter the movie year"><br>
    <input type="file" name="img" ><br>
    <input type="submit">
</form>
{% endblock %}

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movies
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    Do u want to delete this movie?<br>
    <input type="submit">
</form>
{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movies.img.url}}" width="300" height="300"><br>

        </div>
    <div class="col-md-6">
        <h4>{{movies.name}}</h4>
        <h6>{{movies.desc}}</h6>
        <h6>{{movies.year}}</h6>
        <a class="btn btn-warning" href="{% url 'movieapp:update' movies.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movies.id %}">delete</a>
    </div>
 </div>
</div>



{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list%}
      <div class="col-md-3">
          <div class="card">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="200px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">View Details</a>
  </div>
</div>
      </div>
        {% endfor %}


    </div>
</div>
<a class="btn btn-info" href="{% url 'movieapp:add_movie' %}">Add movie</a>





{% endblock %}

<!--<br><img src='{{i.img.url}}' width="100" height="100">-->
<!--<a href="{% url 'movieapp:detail' i.id %}"><button>{{i.name}}</button></a><br><br>-->

<!--<a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">Add movie</a>-->

